"""
Agent service — AI-powered article generation.

run_generation() is designed to be called as a FastAPI BackgroundTask.
It runs synchronously (blocking), which is fine inside FastAPI's background
task threadpool.
"""
from __future__ import annotations

import backend.store as store
import backend.services.cli_runner as runner

# ─── Skill system prompts ─────────────────────────────────────────────────────

_SKILL_INSTRUCTIONS: dict[str, str] = {
    "deep-dive":
        ("Write a technical deep-dive article. Include concrete code examples, "
         "explain the underlying mechanisms, cover edge cases, and reference real-world usage."),
    "tutorial": ("Write a step-by-step tutorial. Cover prerequisites, walk through a real "
                 "implementation from scratch, highlight common pitfalls, and show how to verify "
                 "the result works."),
    "comparison":
        ("Write a comparison article. Cover setup complexity, performance characteristics, "
         "developer experience, and ecosystem maturity. Include a summary table. "
         "End with a recommendation for different scenarios."),
    "opinion": ("Write an opinion piece. Lead with a clear thesis, support it with specific "
                "evidence and examples, acknowledge counterarguments, and close with a takeaway."),
}


def _build_prompt(brief: str, skill: str, word_count: int) -> str:
    instructions = _SKILL_INSTRUCTIONS.get(skill, _SKILL_INSTRUCTIONS["deep-dive"])
    return ("You are a technical writer producing a blog article for a developer audience.\n\n"
            f"{instructions}\n\n"
            f"Target length: approximately {word_count} words.\n\n"
            "Output the article in Markdown. The first line must be a # Title. "
            "Write the complete article — do not stop early or add any commentary "
            "outside the article itself.\n\n"
            f"Author's brief:\n{brief}")


def _extract_title(markdown: str) -> str:
    for line in markdown.splitlines():
        stripped = line.strip()
        if stripped.startswith("# "):
            return stripped[2:].strip()
    return "Untitled Article"


# ─── Provider name mapping ────────────────────────────────────────────────────

_PROVIDER_MAP = {"claude": "anthropic", "codex": "openai"}

# ─── Main background task ─────────────────────────────────────────────────────


def run_generation(
    *,
    user_id: str,
    job_id: str,
    article_id: str,
    brief: str,
    skill: str,
    provider: str,  # "claude" or "codex" (UI values)
    word_count: int,
    context_text: str | None,
    destinations: list[str],
    session_id: str | None = None,
) -> None:
    """
    Called as a FastAPI BackgroundTask after POST /api/agent/generate returns 202.

    On success:
        - writes generated markdown to the article body
        - extracts and saves the article title from the first # heading
        - marks selected destinations as pending
        - completes the job with status=done

    On any failure:
        - completes the job with status=error and an error message
    """
    runner_provider = _PROVIDER_MAP.get(provider, provider)
    full_prompt = _build_prompt(brief, skill, word_count)
    if context_text:
        full_prompt += f"\n\nAdditional context:\n{context_text}"

    token = store.get_connection_token(user_id, runner_provider) if runner_provider == "openai" else None
    api_key = runner.api_key_from_connection_token(token)

    try:
        result = runner.run_task(
            provider=runner_provider,
            task="generate",
            article_md=full_prompt,
            context_md=context_text if context_text else None,
            api_key=api_key,
        )
    except runner.RunnerUnavailable as exc:
        store.complete_job(user_id, job_id, error=str(exc))
        if session_id:
            store.update_agent_session_status(user_id, session_id, "failed", str(exc))
        return

    if result.get("exit_code", 1) != 0:
        err = (result.get("stderr") or result.get("stdout") or "unknown error")[:500]
        store.complete_job(user_id, job_id, error=f"Generation failed: {err}")
        if session_id:
            store.update_agent_session_status(
                user_id, session_id, "failed", f"Generation failed: {err}"
            )
        return

    generated_md: str = result.get("stdout", "")
    if not generated_md.strip():
        store.complete_job(user_id, job_id, error="Generation produced empty output")
        if session_id:
            store.update_agent_session_status(
                user_id, session_id, "failed", "Generation produced empty output"
            )
        return

    title = _extract_title(generated_md)
    store.save_article_revision(
        user_id,
        article_id,
        title=title if title != "Untitled Article" else None,
        content=generated_md,
        source="agent",
        description="Article generated by AI",
    )

    if destinations:
        store.set_destinations_pending(user_id, article_id, destinations)

    word_count_actual = len(generated_md.split())
    store.complete_job(user_id, job_id, result={"wordCount": word_count_actual, "title": title})
    if session_id:
        store.add_agent_message(user_id, session_id, "assistant", generated_md)
        store.add_agent_output(
            user_id, session_id, kind="article", reference=article_id,
            metadata={"word_count": word_count_actual, "title": title},
        )
        store.update_agent_session_status(user_id, session_id, "completed")
