"""AI generation logic shared by durable worker handlers."""
from __future__ import annotations

import backend.services.cli_runner as runner

store = None


class GenerationError(RuntimeError):
    pass

# ─── Skill system prompts ─────────────────────────────────────────────────────

_SKILL_INSTRUCTIONS: dict[str, str] = {
    "deep-dive":
        ("Write a technical deep-dive article. Include concrete code examples, "
         "explain the underlying mechanisms, cover edge cases, and reference real-world usage."),
    "tutorial": ("Write a step-by-step tutorial. Cover prerequisites, walk through a real "
                 "implementation from scratch, highlight common pitfalls, and show how to verify "
                 "the result works."),
    "comparison":
        ("Write a comparison article. Cover setup complexity, performance characteristics, "
         "developer experience, and ecosystem maturity. Include a summary table. "
         "End with a recommendation for different scenarios."),
    "opinion": ("Write an opinion piece. Lead with a clear thesis, support it with specific "
                "evidence and examples, acknowledge counterarguments, and close with a takeaway."),
}


def _build_prompt(brief: str, skill: str, word_count: int) -> str:
    instructions = _SKILL_INSTRUCTIONS.get(skill, _SKILL_INSTRUCTIONS["deep-dive"])
    return ("You are a technical writer producing a blog article for a developer audience.\n\n"
            f"{instructions}\n\n"
            f"Target length: approximately {word_count} words.\n\n"
            "Output the article in Markdown. The first line must be a # Title. "
            "Write the complete article — do not stop early or add any commentary "
            "outside the article itself.\n\n"
            f"Author's brief:\n{brief}")


def _extract_title(markdown: str) -> str:
    for line in markdown.splitlines():
        stripped = line.strip()
        if stripped.startswith("# "):
            return stripped[2:].strip()
    return "Untitled Article"


# ─── Provider name mapping ────────────────────────────────────────────────────

_PROVIDER_MAP = {"claude": "anthropic", "codex": "openai"}

# ─── Generation steps ────────────────────────────────────────────────────────


def generate_markdown(
    storage,
    *,
    user_id: str,
    brief: str,
    skill: str,
    provider: str,
    word_count: int,
    context_text: str | None,
) -> str:
    """Call the configured provider without mutating article or job state."""
    runner_provider = _PROVIDER_MAP.get(provider, provider)
    full_prompt = _build_prompt(brief, skill, word_count)
    if context_text:
        full_prompt += f"\n\nAdditional context:\n{context_text}"
    api_key = (
        storage.get_connection_token(user_id, runner_provider)
        if runner_provider == "openai" else None
    )
    try:
        result = runner.run_task(
            provider=runner_provider,
            task="generate",
            article_md=full_prompt,
            context_md=context_text if context_text else None,
            api_key=api_key,
        )
    except runner.RunnerUnavailable as exc:
        raise GenerationError(str(exc)) from exc
    if result.get("exit_code", 1) != 0:
        error = (result.get("stderr") or result.get("stdout") or "unknown error")[:500]
        raise GenerationError(f"Generation failed: {error}")
    generated = result.get("stdout", "")
    if not generated.strip():
        raise GenerationError("Generation produced empty output")
    return generated


def persist_generation(
    storage,
    *,
    user_id: str,
    article_id: str,
    generated_markdown: str,
    destinations: list[str],
    session_id: str | None,
) -> dict:
    """Apply provider output idempotently to BlogHub-owned state."""
    title = _extract_title(generated_markdown)
    storage.update_article_body(
        user_id, article_id, generated_markdown, event="Article generated by AI"
    )
    if title != "Untitled Article":
        storage.update_article_title(user_id, article_id, title)
    if destinations:
        storage.set_destinations_pending(user_id, article_id, destinations)
    word_count_actual = len(generated_markdown.split())
    if session_id:
        session = storage.get_agent_session(user_id, session_id)
        already_recorded = session and any(
            output["kind"] == "article" and output["reference"] == article_id
            for output in session["outputs"]
        )
        if not already_recorded:
            storage.add_agent_message(
                user_id, session_id, "assistant", generated_markdown
            )
            storage.add_agent_output(
                user_id, session_id, kind="article", reference=article_id,
                metadata={"word_count": word_count_actual, "title": title},
            )
        storage.update_agent_session_status(user_id, session_id, "completed")
    return {"wordCount": word_count_actual, "title": title}


# Kept as a compatibility entry point for callers outside the API router.


def run_generation(
    *,
    user_id: str,
    job_id: str,
    article_id: str,
    brief: str,
    skill: str,
    provider: str,  # "claude" or "codex" (UI values)
    word_count: int,
    context_text: str | None,
    destinations: list[str],
    session_id: str | None = None,
) -> None:
    storage = store
    if storage is None:
        import backend.store as storage

    try:
        generated = generate_markdown(
            storage, user_id=user_id, brief=brief, skill=skill, provider=provider,
            word_count=word_count, context_text=context_text,
        )
        result = persist_generation(
            storage, user_id=user_id, article_id=article_id,
            generated_markdown=generated, destinations=destinations,
            session_id=session_id,
        )
    except GenerationError as exc:
        storage.complete_job(user_id, job_id, error=str(exc))
        if session_id:
            storage.update_agent_session_status(user_id, session_id, "failed", str(exc))
        return
    storage.complete_job(user_id, job_id, result=result)
