"""
ArticleStore Protocol — the contract every storage backend must satisfy.

Routers import from backend.store (the __init__), never from this file directly.
This file exists so mypy can verify that a new backend implements every method
before it ships.
"""
from __future__ import annotations

from datetime import timedelta
from pathlib import Path
from typing import Any, Protocol


class ArticleStore(Protocol):
    # ── Articles ─────────────────────────────────────────────────────────────

    def list_articles(
        self,
        user_id: str,
        q: str | None = None,
        gate: str | None = None,
        status: str | None = None,
        platform: str | None = None,
        page: int = 1,
        page_size: int = 20,
        sort_by: str = "updatedAt",
        sort_dir: str = "desc",
    ) -> tuple[list[dict], int]:
        ...

    def get_article(self, user_id: str, article_id: str) -> dict | None:
        ...

    def create_article(
        self,
        user_id: str,
        title: str,
        source: str = "native",
        source_platform: str | None = None,
        canonical_url: str | None = None,
    ) -> dict:
        ...

    def create_imported_article(
        self,
        user_id: str,
        title: str,
        body: str,
        source_platform: str,
        canonical_url: str | None = None,
        remote_updated_at: str | None = None,
    ) -> dict:
        ...

    def get_or_create_remote_article(
        self,
        user_id: str,
        platform: str,
        remote_id: str,
        *,
        title: str,
        body: str,
        canonical_url: str | None = None,
        remote_updated_at: str | None = None,
    ) -> tuple[dict, bool]:
        ...

    def sync_remote_article_metadata(
        self,
        user_id: str,
        article_id: str,
        *,
        platform: str,
        status: str,
        url: str | None,
        remote_id: str,
        canonical_url: str | None,
        remote_updated_at: str | None,
    ) -> bool:
        ...

    def update_article_body(self, user_id: str, article_id: str, body: str, event: str = "Article generated by AI") -> None:
        ...

    def save_article_revision(self, user_id: str, article_id: str, **kwargs) -> dict:
        ...

    def get_current_article_revision(self, user_id: str, article_id: str) -> dict | None:
        ...

    def list_article_revisions(self, user_id: str, article_id: str) -> list[dict]:
        ...

    def get_article_revision(
        self, user_id: str, article_id: str, revision_id: str
    ) -> dict | None:
        ...

    def compare_article_revision(
        self, user_id: str, article_id: str, revision_id: str
    ) -> dict | None:
        ...

    def restore_article_revision(
        self,
        user_id: str,
        article_id: str,
        revision_id: str,
        expected_revision_id: str,
    ) -> dict:
        ...

    def store_asset(
        self,
        article_id: str,
        filename: str,
        data: bytes,
        mime_type: str | None,
    ) -> str:
        ...

    def read_article_asset(
        self, user_id: str, article_id: str, asset_id: int,
    ) -> dict | None:
        ...

    def get_article_asset_by_filename(
        self, user_id: str, article_id: str, filename: str,
    ) -> dict | None:
        ...

    def delete_articles(self, user_id: str, ids: list[str], force: bool = False) -> list[str]:
        ...

    def duplicate_article(
        self, user_id: str, article_id: str, idempotency_key: str,
    ) -> tuple[dict | None, bool]:
        ...

    def archive_article(
        self, user_id: str, article_id: str, idempotency_key: str | None = None,
    ) -> bool:
        ...

    def delete_article(
        self, user_id: str, article_id: str, idempotency_key: str | None = None,
    ) -> str:
        ...

    def find_article_by_canonical_url(self, canonical_url: str) -> dict | None:
        ...

    def find_article_by_title(self, title: str) -> dict | None:
        ...

    def merge_platform_into_article(
        self,
        article_id: str,
        platform: str,
        status: str,
        url: str | None,
        draft_id: str | None,
        event: str,
    ) -> dict:
        ...

    def apply_inspect_result(self, article_id: str, gate: str) -> None:
        ...

    def apply_push_result(
        self,
        article_id: str,
        platform: str,
        success: bool,
        url: str | None,
        error: str | None,
        label: str | None,
        draft_id: str | None,
        status: str | None = None,
    ) -> None:
        ...

    def set_destinations_pending(self, article_id: str, platforms: list[str]) -> None:
        ...

    # ── Remote article identity ──────────────────────────────────────────────

    def get_remote_article_identity(
        self, user_id: str, platform: str, remote_id: str,
    ) -> dict | None:
        ...

    def list_article_remote_identities(
        self, user_id: str, article_id: str,
    ) -> list[dict]:
        ...

    def upsert_remote_article_identity(
        self, user_id: str, article_id: str, platform: str, remote_id: str,
        **kwargs: Any,
    ) -> dict:
        ...

    def record_reconciliation_observation(
        self, user_id: str, article_id: str, platform: str, remote_id: str,
        **kwargs: Any,
    ) -> dict:
        ...

    def get_reconciliation_observation(
        self, user_id: str, article_id: str, observation_id: str,
    ) -> dict | None:
        ...

    def get_latest_reconciliation_observation(
        self, user_id: str, article_id: str, platform: str,
    ) -> dict | None:
        ...

    def list_latest_reconciliation_observations(
        self, user_id: str, article_id: str,
    ) -> list[dict]:
        ...

    def has_unresolved_reconciliation(
        self, user_id: str, article_id: str, platforms: list[str] | None = None,
    ) -> bool:
        ...

    # ── Connections ──────────────────────────────────────────────────────────

    def list_connections(self, user_id: str) -> list[dict]:
        ...

    def save_connection(
        self,
        user_id: str,
        conn_id: str,
        token: str,
        status: str = "connected",
        username: str | None = None,
        error: str | None = None,
    ) -> dict:
        ...

    def delete_connection(self, user_id: str, conn_id: str) -> None:
        ...

    def get_connection_token(self, user_id: str, conn_id: str) -> str | None:
        ...

    def count_connected(self, user_id: str) -> int:
        ...

    def create_connection_auth_flow(
        self, user_id: str, provider: str, flow_type: str, **kwargs: Any,
    ) -> dict:
        ...

    def get_connection_auth_flow(self, user_id: str, flow_id: str) -> dict | None:
        ...

    def get_latest_connection_auth_flow(
        self, user_id: str, provider: str, *, active_only: bool = False,
    ) -> dict | None:
        ...

    def list_active_connection_auth_flows(self, user_id: str) -> list[dict]:
        ...

    def update_connection_auth_flow(
        self, user_id: str, flow_id: str, status: str, **kwargs: Any,
    ) -> dict:
        ...

    def delete_connection_auth_flows(self, user_id: str, provider: str) -> int:
        ...

    def create_oauth_state(self, conn_id: str) -> str:
        ...

    def consume_oauth_state(self, state: str, conn_id: str) -> bool:
        ...

    # ── Platforms ────────────────────────────────────────────────────────────

    def list_platforms(self) -> list[dict]:
        ...

    # ── Jobs ─────────────────────────────────────────────────────────────────

    def create_job(
        self, user_id: str, job_type: str, article_id: str | None,
        payload: dict | None = None, **kwargs: Any,
    ) -> dict:
        ...

    def get_job(self, user_id: str, job_id: str) -> dict | None:
        ...

    def find_job_by_idempotency_key(
        self, user_id: str, job_type: str, idempotency_key: str | None,
    ) -> dict | None:
        ...

    def list_jobs(self, user_id: str, **kwargs: Any) -> list[dict]:
        ...

    def request_job_cancellation(self, user_id: str, job_id: str) -> dict | None:
        ...

    def retry_job(self, user_id: str, job_id: str) -> dict | None:
        ...

    def upsert_sync_schedule(
        self, user_id: str, platform: str, interval_seconds: int,
        *, enabled: bool = True,
    ) -> dict:
        ...

    def list_sync_schedules(self, user_id: str) -> list[dict]:
        ...

    def ensure_connected_sync_schedules(
        self, user_id: str | None = None, *, interval_seconds: int = 60,
    ) -> list[dict]:
        ...

    def enqueue_due_sync_jobs(self) -> int:
        ...

    def delete_sync_schedule(self, user_id: str, platform: str) -> bool:
        ...

    # ── Browser publishing ──────────────────────────────────────────────────

    def create_browser_publish_run(
        self, user_id: str, article_id: str, *, platform: str,
        mode: str = "draft",
    ) -> dict:
        ...

    def get_browser_publish_run(self, user_id: str, run_id: str) -> dict | None:
        ...

    def approve_browser_publish_run(self, user_id: str, run_id: str) -> dict:
        ...

    def complete_browser_publish_run(
        self, user_id: str, run_id: str, *, result: dict | None = None,
        error: str | None = None,
    ) -> dict:
        ...

    def recover_browser_publish_runs(self) -> int:
        ...

    # ── Browser connections ────────────────────────────────────────────────

    def get_browser_connection(self, user_id: str, platform: str) -> dict | None:
        ...

    def get_reusable_browser_profile(
        self, user_id: str, platform: str,
    ) -> dict | None:
        ...

    def start_browser_connection(self, user_id: str, platform: str, **kwargs: Any) -> dict:
        ...

    def update_browser_connection(
        self, user_id: str, platform: str, status: str, **kwargs: Any
    ) -> dict:
        ...

    def delete_browser_connection(self, user_id: str, platform: str) -> bool:
        ...

    def disconnect_browser_connection(
        self, user_id: str, platform: str,
    ) -> dict | None:
        ...

    def complete_job(self, user_id: str, job_id: str, result: dict | None = None, error: str | None = None) -> None:
        ...

    # ── Agent sessions ──────────────────────────────────────────────────────

    def create_agent_session(self, user_id: str, **kwargs: Any) -> dict:
        ...

    def list_agent_sessions(self, user_id: str, **kwargs: Any) -> list[dict]:
        ...

    def get_agent_session(self, user_id: str, session_id: str) -> dict | None:
        ...

    def add_agent_message(
        self, user_id: str, session_id: str, role: str, content: str,
        metadata: dict | None = None,
    ) -> dict:
        ...

    def add_agent_event(
        self, user_id: str, session_id: str, kind: str, data: Any = None,
    ) -> dict:
        ...

    def record_agent_tool_call(
        self, user_id: str, session_id: str, **kwargs: Any,
    ) -> tuple[dict, bool]:
        ...

    def claim_agent_tool_call(self, user_id: str, session_id: str, tool_call_id: str) -> bool:
        ...

    def complete_agent_tool_call(
        self, user_id: str, session_id: str, tool_call_id: str,
        *, result: Any = None, error: str | None = None,
    ) -> dict:
        ...

    def add_agent_checkpoint(self, user_id: str, session_id: str, state: dict) -> dict:
        ...

    def request_agent_approval(
        self, user_id: str, session_id: str, request: dict,
        tool_call_id: str | None = None,
    ) -> dict:
        ...

    def resolve_agent_approval(
        self, user_id: str, session_id: str, approval_id: str, *, approved: bool,
        response: dict | None = None,
    ) -> dict:
        ...

    def add_agent_output(
        self, user_id: str, session_id: str, *, kind: str, reference: str,
        metadata: dict | None = None,
    ) -> dict:
        ...

    def update_agent_session_status(
        self, user_id: str, session_id: str, status: str, error: str | None = None,
    ) -> dict:
        ...

    def resume_agent_session(self, user_id: str, session_id: str) -> dict:
        ...

    def cancel_agent_session(self, user_id: str, session_id: str) -> dict:
        ...

    def archive_agent_session(self, user_id: str, session_id: str) -> dict:
        ...

    def delete_agent_session(self, user_id: str, session_id: str) -> bool:
        ...

    def export_agent_session(self, user_id: str, session_id: str) -> dict:
        ...

    def recover_agent_sessions(self) -> int:
        ...

    def cleanup_agent_sessions(self, retention_days: int = 90) -> dict[str, int]:
        ...

    # ── Lifecycle ────────────────────────────────────────────────────────────

    @property
    def schema_version(self) -> int:
        ...

    def create_backup(
        self, backup_dir: str | None = None, *, retain: int = 14
    ) -> Path:
        ...

    def create_backup_if_due(
        self,
        interval: timedelta,
        backup_dir: str | None = None,
        *,
        retain: int = 14,
    ) -> Path | None:
        ...

    def close(self) -> None:
        ...

    def reset(self) -> None:
        ...
